name: "Publish package"
on:
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Checkout repository"
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "yarn"
      - name: "Install dependencies"
        run: yarn install --frozen-lockfile
      - name: "Build package"
        run: yarn build
      - name: "Publish package"
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}